### ISSUE TITLE
cannot use emoji window

### ISSUE THREAD

**Issue by jahlbornG** [sbmpost/AutoRaise#114] opened 2022-11-08 13:40 UTC
when i try to enter an emoji using ctrl+cmd+space, the dialog pops up, but after scrolling for a second, the dialog goes away.  i assume this has something to do with autoraise changing focus away from the popup.

**Comment by sbmpost** [comment] 2022-11-10 08:56
@jahlbornG 
Thanks for reporting! Will have a look asap.

**Comment by sbmpost** [comment] 2023-01-01 11:01
@jahlbornG 
So I had a look. If I disable AutoRaise completely, I am still seeing the behaviour you are describing. For example, I am writing some text in the "Notes" application. Then I want to insert a smiley:

- I activate the Emoji popup
- The popup appears with an arrow on top indicating where my smiley is going to be inserted
- I scroll the Notes window
- The popup disappears

> i assume this has something to do with autoraise changing focus away from the popup.
Maybe, but maybe not ;-). So far I can't see different behaviour when I completely disable AutoRaise.

**Comment by jahlbornG** [comment] 2023-01-19 20:48
interesting.

**Comment by sbmpost** [comment] 2023-02-26 15:12
@jahlbornG 
Is it ok to close this issue as it seems unrelated to AutoRaise?

**Comment by jahlbornG** [comment] 2023-03-03 19:22
thanks for taking a look!

**Comment by benjaminhera** [comment] 2023-08-21 09:34
Having the same issue. It is related to AutoRaise, as if I hold `^` while hover over the emoji keyboard it stays there.

I'm sure there is a workaround, by setting up the budleId for the emoji keyboard or something like that.

**Comment by sbmpost** [comment] 2023-08-30 10:08
@benjaminhera 
I checked again, but still can't reproduce. Can you perhaps give the exact steps to execute so I can reproduce?

**Comment by sbmpost** [comment] 2023-09-16 11:41
@benjaminhera @jahlbornG 

I am about to close this issue again. In my last comment you will find a possible solution

**Closed** 2023-09-19 15:54 UTC
Labels: question
