### ISSUE TITLE
Big Sur: All apps windows raises if app have more than one window 

### ISSUE THREAD

**Issue by Dimentium** [sbmpost/AutoRaise#19] opened 2021-01-09 14:04 UTC
Hello again :)

autoraise raise all apps windows instead window under mouse only
I make short video.
Is it possible to fix that or make configurable behaviour ?

Thank you for this tool! 

https://user-images.githubusercontent.com/5391420/104093616-e0c6f880-528b-11eb-9fe8-a9a1272c7ecd.mov

**Comment by sbmpost** [comment] 2021-01-11 10:09
Interesting behaviour. I can't reproduce this (I using Mojave still). From which app are the white windows? Is it Finder?

**Comment by Dimentium** [comment] 2021-01-12 09:39
yep. 
two finder windows, and one terminal. same for two safari windows (my original case) or terminal windows.

**Comment by sbmpost** [comment] 2021-01-12 20:54
@Dimentium you are using the latest version correct? Maybe you can give me some details on the OSX version as well.

**Comment by Dimentium** [comment] 2021-01-12 21:12
> @Dimentium you are using the latest version correct? Maybe you can give me some details on the OSX version as well.

sure!
```
❯ md5 (which autoraise)
MD5 (/usr/local/bin/autoraise) = 59933a5a5afa22a0abf61dde0f73ecea

❯ sw_vers 
ProductName:	macOS
ProductVersion:	11.1
BuildVersion:	20C69
```

**Comment by Dimentium** [comment] 2021-01-12 21:20
now I disable autoraise and enable same feature in yabai
`yabai -m config focus_follows_mouse          autoraise`
and it works properly. but 'yabai' mainteiners don't want to implement 'delay before focus' possibility - that's why I prefer your tool :)
https://user-images.githubusercontent.com/5391420/104375614-f22a3200-5523-11eb-93a4-695e5b82452f.mov

**Comment by sbmpost** [comment] 2021-01-13 10:42
@Dimentium I did some research and found this:

https://stackoverflow.com/questions/65196498/nsrunningapplication-activatewithoptions-method-behavior-change-with-big-sur

So it seems using deprecated APIs, might be a way out of this, but obviously this is a temporary solution as one can never be sure when Apple actually removes those old APIs in their next OSX release. I will investigate this a bit further.

Thanks for reporting!

**Comment by sbmpost** [comment] 2021-01-13 10:56
Can you try with this version?
https://github.com/sbmpost/AutoRaise/raw/8b273a6bb2501e7f4dfbc0958999c76a8a7fe92d/AutoRaise

**Comment by Dimentium** [comment] 2021-01-13 11:52
> Can you try with this version?
> https://github.com/sbmpost/AutoRaise/blob/8b273a6bb2501e7f4dfbc0958999c76a8a7fe92d/AutoRaise

I try it and it works perfect now!
Thank you!

**Comment by sbmpost** [comment] 2021-01-13 18:20
Cool, closing the issue then. Code has been merged to master

**Closed by sbmpost** 2021-01-13 18:20 UTC
