### ISSUE TITLE
Strange behaviour on last build (flicking and return focus to previous window)

### ISSUE THREAD

**Issue by Dimentium** [sbmpost/AutoRaise#33] opened 2021-04-13 18:09 UTC
I complied new build today and got strange behaviour.
Now focus returning to previous window and windows flickering at same time.
Is it only for me?

I make short video: https://www.youtube.com/watch?v=F8uyj8UFYic
and another one: https://youtu.be/KcewIgR4ib8

**Comment by Dimentium** [comment] 2021-04-13 18:28
Hmmm... I delete newly created ~/AutoRaise.wrap and ~/AutoRaise.delay and now current build works correctly.

**Comment by Dimentium** [comment] 2021-04-13 18:28
Same strange behaviour than I run current build with command line parameters:
./autoraise -delay 2 -warpX 0.5 -warpY 0.1 &

**Comment by sbmpost** [comment] 2021-04-14 08:45
@Dimentium
Thanks for reporting and the detailed video! I remember from our last conversation, you are running Big Sur and because I can't reproduce this, my guess is that this is a Big Sur specific problem. So we will have to debug this a bit together if you are okay with this. What happens if you set -delay 1?

    ./autoraise -delay 1 -warpX 0.5 -warpY 0.1 &

Also can you maybe double check you are not running 2 instances at the same time with the Activity Monitor? In the meantime, I will restore a small piece of code that may have something to do with this flickering behaviour and also add versioning information which I noticed you were looking for ;-) I will inform you when I have that branch prepared.

**Comment by sbmpost** [comment] 2021-04-14 09:22
@Dimentium 
Ok, I have a [debug version](https://github.com/sbmpost/AutoRaise/archive/refs/heads/debug-big-sur-warp.zip) prepared. I restored some mouse move checking code, added debug lines and added a switch to enable/disable the scaling of the mouse cursor. By default the scaling is now off. Would be great if you can run this on your machine like so (making sure no previous AutoRaise is already running)

    make && ./AutoRaise -delay 2 -warpX 0.5 -warpY 0.1 -scale true
    
If then you still see the problem, then maybe try with -scale false. And if that doesn't work, the logs it spits out can tell us something about what is going on ;-)

**Comment by Dimentium** [comment] 2021-04-14 19:28
Hi!

Im sure that I don't run tool twice at some time - I check it every time with pgrep and switching between 'old' and 'new' versions for making video and checking behaviour. 

Now debug version works fine without any flickering!

```
~/src/AutoRaise-debug-big-sur-warp took 17s 
❯ ./AutoRaise -delay 2 -warpX 0.5 -warpY 0.1 -scale true

By sbmpost(c) 2021, usage:
AutoRaise -delay <1=20ms> [-warpX <0.5> -warpY <0.5>] -scale <true|false>
Started with 40 ms delay, warpX: 0.5, warpY: 0.1
version 1.7d (debug version), cursor scaling enabled: 1

2021-04-14 20:03:14.985 AutoRaise[62401:747096] event tap enabled
2021-04-14 20:03:17.321 AutoRaise[62401:747096] activated by task switcher
2021-04-14 20:03:17.326 AutoRaise[62401:747096] app activated
2021-04-14 20:03:17.330 AutoRaise[62401:747096] warp the mouse
2021-04-14 20:03:19.515 AutoRaise[62401:747096] activated by task switcher
2021-04-14 20:03:19.522 AutoRaise[62401:747096] app activated
2021-04-14 20:03:19.526 AutoRaise[62401:747096] warp the mouse
2021-04-14 20:03:22.570 AutoRaise[62401:747096] raise/activate
2021-04-14 20:03:23.588 AutoRaise[62401:747096] activated by task switcher
2021-04-14 20:03:23.595 AutoRaise[62401:747096] app activated
2021-04-14 20:03:23.598 AutoRaise[62401:747096] warp the mouse
^C⏎     
```

Yesterday's version works fine with any delay only without Warp parameters. .
If any Warp has been set - I get cursor jumping and focus flickering.
Seems there something wrong with cursor moving (it try to jump when focus changed by mouse moving not only keyboard shortcut).

**Comment by sbmpost** [comment] 2021-04-14 20:26
Interesting. In terms of functionality, the debug version doesn't really change that much apart from the added -scale parameter. Perhaps the master branch was in a wrong state when you downloaded it? To double check this theory, can you download a fresh copy from [here](https://github.com/sbmpost/AutoRaise/archive/refs/heads/master.zip) and see if it also fails when you pass it the warp parameters? It is a bit far fetched, but I can't think of another explanation. Thanks for helping me to sort this out ;-)

**Comment by Dimentium** [comment] 2021-04-14 20:46
> @Dimentium
> Interesting. In terms of functionality, the debug version doesn't really change that much apart from the added -scale parameter. Perhaps the master branch was in a wrong state when you downloaded it? To double check this theory, can you download a fresh copy from [here](https://github.com/sbmpost/AutoRaise/archive/refs/heads/master.zip) and see if it also fails when you pass it the warp parameters? It is a bit far fetched, but I can't think of another explanation. Thanks for helping me to sort this out ;-)

hmm..
I downloaded sources with this url and compile - there is no glitches.
I pull main branch and recompile it - and got same md5 and no glitches!
My bad - I don't saved yesterday's strange build >.<
Very like that I got a wrong state master branch :/

Thank you!!

**Comment by sbmpost** [comment] 2021-04-14 21:38
> My bad - I don't saved yesterday's strange build >.<
Very like that I got a wrong state master branch :/

No worries. In fact you gave me the idea to make the scaling configurable 🙂 
That will be in the next release. Closing this issue.

**Closed** 2021-04-14 21:40 UTC

**Comment by Dimentium** [comment] 2021-04-14 21:42
I don't know is it important, but atm "-scale true" works only if both of -delay and -warps params are defined in command line.
Otherwise it detected as false:

```
❯ ./AutoRaise -delay 2 -scale true

By sbmpost(c) 2021, usage:
AutoRaise -delay <1=20ms> [-warpX <0.5> -warpY <0.5>] -scale <true|false>
Started with 40 ms delay, warpX: 0.5, warpY: 0.5
version 1.7d (debug version), cursor scaling enabled: 0
```
