### ISSUE TITLE
Problem with second display.

### ISSUE THREAD

**Issue by sohate** [sbmpost/AutoRaise#193] opened 2024-03-25 04:11 UTC
I have 2 displays. And when the second display has full-screen app on front, autoraise doesn't work correctly with menubar/bartender 4. When cursor moving to menubar on main display autoraise do focus menubar/bartender 4 on second display.

**Comment by sbmpost** [comment] 2024-03-25 09:54
@sohate 

I am unable to reproduce this. Which version of AutoRaise are you using? Also which settings are enabled? A screen shot of the AutoRaise preferences screen would be helpful. When you say full screen, do you mean full full screen enabled with the green window button? Ah video demonstrating the issue would even be better ;-)

**Comment by sohate** [comment] 2024-03-25 11:30
Here's video for you. The second display is full screen mail app.

https://github.com/sbmpost/AutoRaise/assets/81889148/2c24885b-4d2e-4a19-9248-d65786d00b34

**Comment by sbmpost** [comment] 2024-03-25 16:51
@sohate 

Ok, these details should give me enough to work with. Awesome :-)

**Comment by sbmpost** [comment] 2024-03-26 10:00
@sohate 

So I tried with 2 screens and having full screen apps on both of them. For some reason I can't reproduce it. Maybe something changed in more recent Bartender v4 versions? To exclude this possibilty, maybe you can provide me with the exact version number you are using, which can be found under Bartender Preferences | About menu. Note also that I am running MacOS sonoma myself, so that could be a factor as well. However I did prepare a version of AutoRaise that *might* fix your issue, but I can't test it myself. You can find the binary UI version [here](https://github.com/sbmpost/AutoRaise/blob/fix-top-window-bounds-check/AutoRaise.dmg)

**Comment by sohate** [comment] 2024-03-26 10:05
@sbmpost

Yes, you fixed it. Thank you very much! :)

P.S. My Bartender version:

<img width="1110" alt="Screenshot 2024-03-26 at 19 01 22" src="https://github.com/sbmpost/AutoRaise/assets/81889148/219b6b04-5d20-415b-be34-e7695c24846f">

**Comment by sbmpost** [comment] 2024-03-26 17:20
@sohate 

It was merged to master (v5.0). Thanks for reporting!

**Closed by sbmpost** 2024-03-26 17:20 UTC
