### ISSUE TITLE
File-open dialogs sometimes refuse to say raised

### ISSUE THREAD

**Issue by dreeves** [sbmpost/AutoRaise#13] opened 2020-12-02 00:31 UTC
I don't know how to repro this yet but when it happens it's very frustrating behavior. The mouse will be clearly inside the file-open dialog yet the window behind it will autoraise, making it very hard to use the file-open window (you can still do it if you're very quick).

**Comment by sbmpost** [comment] 2020-12-11 12:56
Let me know if you do find a way to reproduce, as I can't reproduce it either ;-)

**Comment by sbmpost** [comment] 2020-12-14 09:21
@dreeves I actually may have found a way to reproduce this. If you open up a larger background window and then open "System Preferences" and select "Security and Privacy", you will see the window correctly stays on top as it is contained. If however you click anywhere in the "Security and Privacy" screen (making the search box on the top right lose its focus), then the contained window no longer stays on top. So in order for any dialog to work properly, I think it needs at least a focussed element, for otherwise AutoRaise will think the window isn't focussed at all. I am not sure if this is easy to fix, but I will give it some thought.

**Comment by sbmpost** [comment] 2021-02-19 14:44
@dreeves This *might* fix this issue, see [this binary](https://github.com/sbmpost/AutoRaise/raw/c28372b5614ce81de5067e3705fc990ed6a77b31/AutoRaise)

**Comment by dreeves** [comment] 2021-02-19 17:47
Oh! Nice work! This problem actually hasn't recurred for me but... just now, before switching to the new binary, I think I found a way to reproduce a milder version of it:

## Reseminata

1. In Google Chrome, choose "Open File" from the file menu.
2. File-choosing popup modal thing pops up.
3. Move cursor to any other window (another Chrome window or another app, doesn't matter)
4. The other window autoraises fine
5. Move cursor back into file-chooser popup.

## Expectata

Autoraise should happen.

## Resultata

The window from step 3 says focused and raised. If in step 5 you move the cursor to the window from step 1 but outside the file-chooser popup then autoraise works as expected.

---

And.... I just switched to the new binary you linked to and the defectus demonstrandum is exactly the same!

PS: I've lost track of what else may have fixed the original bug I reported back in December at the top of this gissue. Maybe one of the binaries I switched to for suppressing autoraise when the new raised window would completely cover the previously raised window? Or maybe this bug was reported after that, I'm not sure.

**Comment by sbmpost** [comment] 2021-02-20 19:37
@dreeves 
The original issue you posted can be reproduced with for example [LTSPICE](https://ltspice.analog.com/software/LTspice.dmg). This application allows you to make the main window small and if you then open a file dialog it will not be fully contained within the main window. Under these conditions, when your mouse is inside the dialog, as you described, you have to be really fast to select the file. The reason you didn't encounter this issue anymore has to do with the improvement that a smaller window inside a larger one no longer loses its focus. But the issue was still there if aforementioned conditions are met. In conclusion, this PR fixes:

1) dialogs losing focus if the mouse is already inside of it and the dialog is not fully contained within the main window
2) improved mechanism to get the focused window, for example the System Preferences window now also stays on top if it is contained in a larger window.
3) and finally with the improved mechanism in 2) we also got rid of a very obscure/annoying memory leak

Now to get back to your last message, this is actually a new issue ;-). So maybe you can copy your (as always very detailed) description into a new issue? I am closing this issue and merging to master. Thanks for reporting!

**Comment by dreeves** [comment] 2021-02-20 19:51
Done! See #27

**Comment by sbmpost** [comment] 2021-02-20 19:51
Thanks!

**Closed by sbmpost** 2021-02-20 19:51 UTC
