### ISSUE TITLE
Functionality not working with separate instances of Safari

### ISSUE THREAD

**Issue by mlubej** [sbmpost/AutoRaise#37] opened 2021-04-17 20:30 UTC
Hi!

I like the app! I missed the functionality from linux, but I noticed that if I have two separate Safari windows open, it won't work as expected, you still need to physically click to change the focus. Is this intentional or was it missed?

**Comment by Dimentium** [comment] 2021-04-17 20:34
>  I noticed that if I have two separate Safari windows open, it won't work as expected, you still need to physically click to change the focus. Is this intentional or was it missed?

Hi!

Can you make a video with this behaviour?
I can't reproduce it with actual version.

**Comment by mlubej** [comment] 2021-04-17 20:36
You're fast! 

I just noticed this is true only if I run the app via Finder. If I use the CLI tool, it works as I would expect. I'll make the video, sure. :)

**Comment by Dimentium** [comment] 2021-04-17 20:42
> You're fast!
> 
> I just noticed this is true only if I run the app via Finder. If I use the CLI tool, it works as I would expect. I'll make the video, sure. :)

I'm just a user of this app too. :)
And I think video is not necessary because you localised your case cause.

**Comment by sbmpost** [comment] 2021-04-21 17:04
Closing this issue as it has been solved. @mlubej the AutoRaise.app bundle version should also work, perhaps you didn't enable Accessibility access? See the README of this project on how to do that.

**Closed by sbmpost** 2021-04-21 17:04 UTC
