### ISSUE TITLE
Can't click anything inside chrome window on Sonoma 14.4

### ISSUE THREAD

**Issue by suszymon** [sbmpost/AutoRaise#189] opened 2024-03-11 15:27 UTC
I'm using 3 monitors with 3 chrome windows on Sonoma 14.4. At random moments one of the Chrome windows freezes and I can't click anything inside a tab. When I disable AutoRaise, it starts working normally.

Chrome 122.0.6261.112.

**Comment by sbmpost** [comment] 2024-03-12 06:34
@suszymon 

That is certainly incorrect behaviour. Are you able to reproduce this with a single or two monitors as well? Also can you tell me if there is other software running that improves the MacOS UI experience? Another thing that will be helpful is the debug output log. This can be enabled by stopping any AutoRaise instances (you can use activity monitor for that) and starting AutoRaise from the commandline with -verbose true. For example:

    ./AutoRaise -focusDelay 1 -verbose true

Let's find out what is going on because we don't want things to 'hang'.

**Comment by sbmpost** [comment] 2024-03-18 09:19
@suszymon 

I am closing this issue as more feedback is needed

**Closed** 2024-03-18 09:19 UTC
