### ISSUE TITLE
macOS menu interruption on laptop display when connected to external display

### ISSUE THREAD

**Issue by samholmes** [sbmpost/AutoRaise#87] opened 2022-06-21 16:50 UTC
This bug is only repeatable when connected to an external display.

1. Connect Macbook to external display
2. Click on a menu item on the Macbook's display (e.g. Control Center)

**Expected**

The menu opened stays opened. 

**Actual**

The menu is abruptly closed.

Note: The menu stays open you click on the menu bar located on the external display.

**Comment by sbmpost** [comment] 2022-06-22 12:19
@samholmes 

> 1. Connect Macbook to external display

Can you try to restart AutoRaise after you connected the external display? And then see if the menu is still abruptly closed?

**Comment by samholmes** [comment] 2022-06-22 16:48
I ran `brew services restart autoraise` while connected to an external display and the issue persists.

**Comment by sbmpost** [comment] 2022-06-23 18:26
@samholmes 

I think it may have something to do with the "mouse hovering over menubar" detection. Btw, I can't reproduce the behavior you describe with a secondary monitor installed. Is there something special about your setup? For example, does the menubar autohide? Or is the height of the menubar on the second screen different? If you can post a video of the problem that would be great.

**Comment by samholmes** [comment] 2022-06-27 16:40
https://user-images.githubusercontent.com/517469/175990673-727babe9-b347-47a9-a42e-da97c904b3bc.mov

I figured out how to reproduce the issue and what is the cause (shown in the video).

1. Connect a secondary display.
2. Open macOS Displays settings and make sure the secondary display is positioned above the primary Macbook display.
3. Open an app window on the secondary display and maximize it to make sure covers the entire secondary display's screen.
4. Move cursor near or over the primary displays menu bar

**Results**

The application in the secondary display is focused after the cursor hovers over the menu bar (or very near the menu bar).

**Expected**

The cursor does not activate a focus on the window in the secondary display.

**Explanation**

I think the reason for this behavior is that AutoRaise may not be considering the menu bar's space when calculating distance from an app window before activating that window. This may be a coordinance-system issue in macOS when it comes to how the menu-bar is considered. I'm running on a Macbook Pro with the notch (perhaps the notch is a factor in this bug).

**Comment by sbmpost** [comment] 2022-06-28 17:01
@samholmes 
Thanks for these details :-) I will try to reproduce with this new information. It might take some days as I am very busy with daily work. This issue is on my radar however ;-)

**Comment by sbmpost** [comment] 2022-07-07 09:38
@samholmes 
With your detailed instructions I can indeed reproduce this behaviour. As you speculated already, AutoRaise is excluding the menubar when considering a raise. When running AutoRaise from the command line with the verbose flag, it will tell you a menubar correction is being applied. This is required for an opened menu not to disappear while hovering its menu items. This solution works for screens that are organized horizontally, but not so well if organized vertically. I am currently investigating if this can be fixed.

**Comment by sbmpost** [comment] 2022-07-07 09:55
@samholmes 
It turns out the fix is quite easy. I will be releasing a v3.3 soon (after fixing a some other issues as well). If you want a fixed version before the release, all you have to do is removing the -1 on [this line](https://github.com/sbmpost/AutoRaise/blob/f83afeabddbc3714c9b736f6485b6a76c68c9221/AutoRaise.mm#L868):

    mousePoint.y = screenOriginY - 1; // REMOVE THE -1

**Comment by sbmpost** [comment] 2022-07-13 12:49
@samholmes I am closing this issue as the fix for it has been merged into master

**Closed as completed by sbmpost** 2022-07-13 12:49 UTC
