### ISSUE TITLE
Focus doesn't switch for Chrome Apps

### ISSUE THREAD

**Issue by alxs** [sbmpost/AutoRaise#144] opened 2023-06-02 14:24 UTC
Chrome Apps can be created via `⋮ > More Tools > Create Shortcut...` or, for compatible websites such as GitHub, directly via  `⋮ > Install Github...`. AutoRaise fails to recognise such windows and does not switch focus.

**Comment by sbmpost** [comment] 2023-06-02 14:36
@alxs 
I created a github app following your instructions and ticking the checkbox 'open as window'. After doing this I get a Github.app. If I open this app, AutoRaise properly switches focus. In other words. I can't reproduce this. Can you send a short video perhaps?

**Comment by sbmpost** [comment] 2023-06-05 16:47
@alxs 

Any feedback on the above? Or can I close this issue?

**Comment by alxs** [comment] 2023-06-08 12:23
Hey @sbmpost, sorry I missed this. Below is a short video demonstrating the issue. I've also just noticed that when the Chrome App is in the foreground, AutoRaise doesn't switch focus to other apps. You can observe this in the second half of the video.

https://github.com/sbmpost/AutoRaise/assets/15819210/acb79fc8-2557-4a63-b0f8-8fdbc22a81f5

**Comment by sbmpost** [comment] 2023-06-08 20:20
@alxs 

Very strange indeed as I still can't reproduce it. See also this video:

https://github.com/sbmpost/AutoRaise/assets/10278551/a4a5c77d-eb7e-4547-8bec-3e0f5df3060d

Are you compiling AutoRaise yourself? If so, can you tell me which compiler flags you used?
And which MacOS version are you running?
To quickly exclude possible reasons, can you maybe run the app from the latest disk image?
See here: https://github.com/sbmpost/AutoRaise/blob/master/AutoRaise.dmg

P.S. Don't forget to stop any previous instances.

**Comment by alxs** [comment] 2023-06-09 08:40
I just downloaded the latest version and tried again, still with the same behaviour. Note that I'm only using the auto-focus feature, not auto-raise - that might be the difference between our setups here.

**Comment by sbmpost** [comment] 2023-06-12 12:02
@alxs 
> I just downloaded the latest version and tried again, still with the same behaviour. Note that I'm only using the auto-focus feature, not auto-raise - that might be the difference between our setups here.

This is indeed the case.

> AutoRaise fails to recognise such windows and does not switch focus.

I managed to reproduce. AutoRaise will not raise if the window title is empty which apparently includes Chrome generated apps. I am currently experimenting with a [branch](https://github.com/sbmpost/AutoRaise/tree/144-no-longer-exclude-based-on-empty-title) to no longer rely on empty window titles. I am not sure if this branch will make it to master because it might break other cases. So I will be running with these modifications for a while and see if this is an improvement. Of course you can do the same if you want to. To compile with these changes, simply checkout the branch and follow the instructions in the README.

**Comment by sbmpost** [comment] 2023-06-19 11:41
@alxs 

So far I have not found any regressions. I have updated this branch to also provide a newer dmg file which includes the changes. This means the UI with preferences window and all is now also available.

Before releasing this to master, I will be running this for a little while longer, but so far all seems well.
If you have any feedback before releasing this, now is the time ;-)

**Comment by sbmpost** [comment] 2023-06-20 08:15
@alxs 

Testing more with the changes I made, today I found a regression unfortunately. I will try to come up with a solution but this might take a while.

**Comment by sbmpost** [comment] 2023-08-29 21:01
@alxs 

I am getting closer to fixing this nasty problem. I think by the end of this week I should have something workable. Will keep you up to date. See also #152

**Comment by sbmpost** [comment] 2023-08-30 10:54
@alxs 
Can you check with this latest binary?
https://github.com/sbmpost/AutoRaise/blob/151-exclude-zim-window/AutoRaise.dmg

**Comment by alxs** [comment] 2023-09-01 06:15
@sbmpost that seems to work beautifully, I've had zero issues so far. Thanks for giving this so much thought!

**Closed** 2023-09-02 09:57 UTC
Labels: enhancement
